DELETE http://localhost:3003/api/blogs/6464b7e7dfda444af0a9407a
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdG1pa2xpIiwiaWQiOiI2NDYzNzM0ZjA1ODg3NGQzMjc5OTQyOGUiLCJpYXQiOjE2ODQzMjIyNTN9.-20FGe-799z1NPNdBg_PnncPtw1LoTgIQYEAaz15rhw